# Klaszterelemzés {#sec-klaszterelemzes}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
```

Az klaszterelemzés segítségével vizsgált probléma a következő: egy $n$ elemű adatbázisban minden egyes elemhez $p$ darab változó értékei kapcsolódnak; alakítsunk az elemekből csoportokat úgy, hogy a "hasonlóak" egy csoportba kerüljenek. Minden klaszter elemei viszonylag hasonlóak legyenek egymáshoz, de különbözzenek más klaszterek elemeitől. 

Számos eljárás született a klaszteranalízis módszerén belül. Ebben a könyvben két eljárással foglalkozunk részletesen: 

* a hierarchikus eljárásokkal és a 
* K-középpontú klaszteranalízissel.

## Hierarchikus eljárások

A hierarchikus eljárások az egyes személyek, objektumok, esetek közötti távolság meghatározásával kezdődnek. A csoportok, klaszterek kialakítása történhet összevonáson vagy felosztáson alapuló módszerekkel. Az összevonó módszerek abból indulnak ki, hogy minden egyes elem egy önálló csoportot alkot, majd fokozatosan vonják össze az egyelemes csoportokat egyetlen nagy csoportba. Ezzel szemben a lebontó módszerben az összes elem egyetlen csoportba tartozik, és ezt a csoportot osztjuk fel kettő, majd egyre több csoportra addig, amíg minden elem egy önálló csoportot nem alkot. Az összevonó módszernél kezdetben minden egyes elem külön klasztert alkot. A klaszterek a megfigyelési egységek egyre nagyobb klaszeterekbe csoportosításával alakulnak ki. A folyamat addig folytatódik, amíg egyetlen klaszter lesz az egész. A következőkben a legelterjedtebb klaszteralkotó módszereket soroljuk fel:

* Egyszerű lánc, avagy a legközelebbi szomszéd elve
* Teljes lánc, avagy a legtávolabbi szomszéd elve
* Átlagos távolság
* Variancia-módszerek
* Ward-féle eljárás
* Centroidmódszerek
* Szekvenciális küszöbérték módszer
* Párhuzamos küszöbérték módszer
* Optimális felosztás módszere

Jamovi-ban a `snowCluster` csomag segítségével végethetünk klaszterelemzéseket. A csomag telepítése után a `snowCluster / Hiearchical Clustering` vagy `snowCluster / Clustering Dendogram` menüpontokat használjuk.

A jamovi a következő módszereket ismeri:

* ward.D
* ward.D2
* single
* complete
* average


## K-középpontú klaszterelemzés


JÖN.
